# Generado por sandbox/render.py desde overlays/openshift. No editar a mano.
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: inventory-service
  name: inventory-service
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: inventory-service:1.0.0
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/DevopsDay2026/backend-inventory-service.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_S2I_ARTIFACT_DIRS
        value: target/quarkus-app
      - name: S2I_SOURCE_DEPLOYMENTS_FILTER
        value: app lib quarkus quarkus-run.jar
      - name: JAVA_APP_JAR
        value: /deployments/quarkus-run.jar
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/openjdk-21:latest
    type: Source
  successfulBuildsHistoryLimit: 2
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: orders-service
  name: orders-service
spec:
  failedBuildsHistoryLimit: 2
  output:
    to:
      kind: ImageStreamTag
      name: orders-service:1.0.0
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  runPolicy: Serial
  source:
    git:
      ref: main
      uri: https://github.com/DevopsDay2026/backend-orders-service.git
    type: Git
  strategy:
    sourceStrategy:
      env:
      - name: MAVEN_S2I_ARTIFACT_DIRS
        value: target/quarkus-app
      - name: S2I_SOURCE_DEPLOYMENTS_FILTER
        value: app lib quarkus quarkus-run.jar
      - name: JAVA_APP_JAR
        value: /deployments/quarkus-run.jar
      from:
        kind: DockerImage
        name: registry.access.redhat.com/ubi9/openjdk-21:latest
    type: Source
  successfulBuildsHistoryLimit: 2
