apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
  labels:
    app.kubernetes.io/name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: orders-service
    spec:
      containers:
        - name: orders-service
          image: orders-service
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-service-config
            - secretRef:
                name: orders-service-secrets
          startupProbe:
            httpGet:
              path: /q/health/started
              port: 8080
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 96Mi
            limits:
              memory: 256Mi
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
