apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/part-of: orders-app
    includeTemplates: true

resources:
  - orders-service/configmap.yaml
  - orders-service/deployment.yaml
  - orders-service/service.yaml
  - inventory-service/configmap.yaml
  - inventory-service/deployment.yaml
  - inventory-service/service.yaml
